#!/usr/bin/env node
// Single source-of-truth version syncer.
//
// ``pyproject.toml`` is the canonical version for the entire Ember
// Code project. The JetBrains plugin reads it via a Gradle task that
// writes ``META-INF/ember-version.properties`` into the plugin JAR;
// this script does the equivalent for the Node-based VSCode (and any
// other future Node) client by generating a TypeScript constant.
//
// Run from anywhere — the script resolves paths relative to itself.
//
//   node scripts/sync-version.mjs
//
// Idempotent: writes only if the generated file is missing or out
// of date, so re-running in CI between npm-install and tsc doesn't
// touch mtime needlessly.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");

const pyprojectPath = join(repoRoot, "pyproject.toml");
const pyproject = readFileSync(pyprojectPath, "utf8");

// Permissive line-level match — the only ``version = "…"`` at the top
// of ``[project]`` is the package's own. We deliberately don't pull in
// a TOML parser to keep this script dep-free.
const versionMatch = pyproject.match(/^\s*version\s*=\s*"([^"]+)"/m);
if (!versionMatch) {
  console.error("could not find version in pyproject.toml");
  process.exit(1);
}
const igniteEmberVersion = versionMatch[1];

// Two kinds of targets:
//
//   • ``write`` — full file generated from a template. Used for the
//     VSCode extension's TS constant since the file exists only to
//     hold the value.
//   • ``patch`` — surgical regex replacement against an existing
//     file. Used for ``package.json`` and ``__init__.py`` so the
//     surrounding content (and formatting) stays untouched. The
//     pattern's capture groups frame the literal that gets swapped.
const targets = [
  {
    kind: "write",
    label: "VSCode extension (runtime constant)",
    path: join(repoRoot, "clients/vscode/src/version.generated.ts"),
    contents:
      "// AUTO-GENERATED by scripts/sync-version.mjs — do not edit.\n" +
      "// Source of truth: pyproject.toml ``version`` field.\n" +
      `export const IGNITE_EMBER_VERSION = ${JSON.stringify(igniteEmberVersion)};\n`,
  },
  {
    kind: "patch",
    label: "VSCode extension (package.json)",
    path: join(repoRoot, "clients/vscode/package.json"),
    // Anchor on the first ``"version": "…"`` line — package.json
    // convention puts the package version near the top, well before
    // any ``engines.vscode`` or dep ``"version":"…"`` would appear.
    pattern: /("version"\s*:\s*")[^"]+(")/,
  },
  {
    kind: "patch",
    label: "Python package (__init__.py)",
    path: join(repoRoot, "src/ember_code/__init__.py"),
    pattern: /(__version__\s*=\s*")[^"]+(")/,
  },
];

let changed = 0;
for (const t of targets) {
  if (t.kind === "write") {
    const current = existsSync(t.path) ? readFileSync(t.path, "utf8") : null;
    if (current === t.contents) continue;
    writeFileSync(t.path, t.contents);
    console.log(`updated ${t.label}: ${t.path}`);
    changed++;
    continue;
  }
  // ``patch``
  const before = existsSync(t.path) ? readFileSync(t.path, "utf8") : null;
  if (before === null) {
    console.error(`missing target file: ${t.path}`);
    process.exit(1);
  }
  if (!t.pattern.test(before)) {
    console.error(`version pattern not found in ${t.path}`);
    process.exit(1);
  }
  const after = before.replace(t.pattern, `$1${igniteEmberVersion}$2`);
  if (after === before) continue;
  writeFileSync(t.path, after);
  console.log(`updated ${t.label}: ${t.path}`);
  changed++;
}
if (changed === 0) console.log(`version ${igniteEmberVersion} already in sync`);
